# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d66f2a6083f8b6583842859fb2cde142d2800bc8f3feb85edbd7b0bcf52994fa27cc9c598adbb7176d9cec91df444bd60873b70711ddb38caec9e6d9e59ff1d6

test:
  secret_key_base: 982152109ffc1c77e7c0cf6deb37ced1921007ea72e4153033e0287304abe7ec78dcd031d2ddfdefcbeced65cffc96c57143d6803fc109d1efc8f15be4baa8da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
